skip-check:

  #================================================================================================
  # Management
  #================================================================================================
  # [CKV_TF_1] Ensure Terraform module sources use a commit hash
  - CKV_TF_1 # This is not required in nonprod.
